// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetControllers() {
  return window['go']['main']['App']['GetControllers']();
}

export function GetDetails(arg1) {
  return window['go']['main']['App']['GetDetails'](arg1);
}

export function Reload() {
  return window['go']['main']['App']['Reload']();
}
