// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetControllers():Promise<Array<string>>;

export function GetDetails(arg1:string):Promise<Array<main.UniverseDetail>>;

export function Reload():Promise<void>;
